apiVersion: v2
appVersion: "1.0"
description: Divorce - Case data formatter Service
name: div-cfs
version: 2.0.9
dependencies:
  - name: java
    version: 4.0.9
    repository: "https://hmctspublic.azurecr.io/helm/v1/repo/"
